rails/chimichanga/config/routes.rb
Chimichanga::Application.routes.draw do
  resources :parties

  resources :snacks

end

rails/chimichanga/app/models/party.rb
class Party < ActiveRecord::Base
   # has_many :snacks
   
   #party = Party.find(10)
   #party.snacks

end

rails/chimichanga/app/models/snack.rb
class Snack < ActiveRecord::Base
  validates_presence_of :name, :message=>' tiene que tener algo'
  validates_presence_of :price, :ingredients
  
  validates_numericality_of :price, :only_integer => true
  
  attr_accessor :date
  # party_id
  #belongs_to :party
end

rails/chimichanga/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails/chimichanga/app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  # GET /parties
  # GET /parties.xml
  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.xml
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.xml
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.xml
  def create
    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        format.html { redirect_to(@party, :notice => 'Party was successfully created.') }
        format.xml  { render :xml => @party, :status => :created, :location => @party }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @party.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.xml
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to(@party, :notice => 'Party was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @party.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.xml
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to(parties_url) }
      format.xml  { head :ok }
    end
  end
end

rails/chimichanga/app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  # GET /snacks
  # GET /snacks.xml
  def index
    @snacks = Snack.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @snacks }
    end
  end

  # GET /snacks/1
  # GET /snacks/1.xml
  def show
    @snack = Snack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snack }
    end
  end

  # GET /snacks/new
  # GET /snacks/new.xml
  def new
    @snack = Snack.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snack }
    end
  end

  # GET /snacks/1/edit
  def edit
    @snack = Snack.find(params[:id])
  end

  # POST /snacks
  # POST /snacks.xml
  def create
    Rails.logger.error "---- #{params.inspect}"
    @snack = Snack.new(params[:snack])
    puts "---- #{@snack.inspect}"
	
	respond_to do |format|
	  if @snack.save
		puts "---- #{@snack.inspect}"
		format.html { redirect_to(@snack, :notice => 'Snack was successfully created.') }
		format.xml  { render :xml => @snack, :status => :created, :location => @snack }
	  else
		format.html { render :action => "new" }
		format.xml  { render :xml => @snack.errors, :status => :unprocessable_entity }
	  end
	end
  end

  # PUT /snacks/1
  # PUT /snacks/1.xml
  def update
    @snack = Snack.find(params[:id])

    respond_to do |format|
      if @snack.update_attributes(params[:snack])
        format.html { redirect_to(@snack, :notice => 'Snack was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snack.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snacks/1
  # DELETE /snacks/1.xml
  def destroy
    @snack = Snack.find(params[:id])
    @snack.destroy

    respond_to do |format|
      format.html { redirect_to(snacks_url) }
      format.xml  { head :ok }
    end
  end
end

rails/chimichanga/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/chimichanga/app/helpers/parties_helper.rb
module PartiesHelper
end

rails/chimichanga/app/helpers/snacks_helper.rb
module SnacksHelper
end

rails/chimichanga/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chimichanga</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/chimichanga/app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :byod %><br />
    <%= f.check_box :byod %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/chimichanga/app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

rails/chimichanga/app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Capacity</th>
    <th>Byod</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td><%= party.address %></td>
    <td><%= party.capacity %></td>
    <td><%= party.byod %></td>
    <td><%= party.price %></td>
    <td><%= link_to 'Show', party %></td>
    <td><%= link_to 'Edit', edit_party_path(party) %></td>
    <td><%= link_to 'Destroy', party, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Party', new_party_path %>

rails/chimichanga/app/views/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

rails/chimichanga/app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @party.address %>
</p>

<p>
  <b>Capacity:</b>
  <%= @party.capacity %>
</p>

<p>
  <b>Byod:</b>
  <%= @party.byod %>
</p>

<p>
  <b>Price:</b>
  <%= @party.price %>
</p>


<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

rails/chimichanga/app/views/snacks/_form.html.erb
<%= form_for(@snack) do |f| %>
  <% if @snack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>

      <ul>
      <% @snack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "mi nombre superoderoso" %><br />
    <%= f.text_field :name, :class=>'formulario', :style=>'color:RED;', :snack=>'hola' %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/chimichanga/app/views/snacks/edit.html.erb
<h1>Editing snack</h1>

<%= render 'form' %>

<%= link_to 'Show', @snack %> |
<%= link_to 'Back', snacks_path %>

rails/chimichanga/app/views/snacks/index.html.erb
<h1>Listing snacks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Size</th>
    <th>Ingredients</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snacks.each do |snack| %>
  <tr>
    <td style='color:#567890'><%= snack.name %></td>
    <td style='background-color:#567890'><%= snack.price %></td>
    <td><%= snack.size %></td>
    <td><%= snack.ingredients %></td>
    <td><%= link_to 'Show', snack %></td>
    <td><%= link_to 'Edit', edit_snack_path(snack) %></td>
    <td><%= link_to 'Destroy', snack, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snack', new_snack_path %>

rails/chimichanga/app/views/snacks/new.html.erb
<h1>New snack</h1>

<%= render 'form' %>

<%= link_to 'Back', snacks_path %>

rails/chimichanga/app/views/snacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @snack.name %>
</p>

<p>
  <b>Price:</b>
  <%= @snack.price %>
</p>

<p>
  <b>Size:</b>
  <%= @snack.size %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @snack.ingredients %>
</p>


<%= link_to 'Edit', edit_snack_path(@snack) %> |
<%= link_to 'Back', snacks_path %>